### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by DaYzTm** [pxwxnvermx/memeboi#2]
Every time I run the code, everything is fine, but when he tries to download the post reddit gallery, he crashes, can this problem be solved?
![2022-04-12 22_11_38-Readme md - Visual Studio Code](https://user-images.githubusercontent.com/64908972/163036212-c6d0e44b-9cdd-4214-9e3f-e6aeb8e2414c.png)

**Comment by pxwxnvermx** [comment]
@DaYzTm Hey, I havent yet implemented support for gallery. I will try to find a solution for this or implement this in some time. Thanks for raising an issue. If you want to you can go ahead and raise a pr fixing this issue.

**Comment by DaYzTm** [comment]
> @DaYzTm Hey, I havent yet implemented support for gallery. I will try to find a solution for this or implement this in some time. Thanks for raising an issue. If you want to you can go ahead and raise a pr fixing this issue.
> 

I will be very pleased if this really happens soon, I am very grateful to you :)

**Comment by DaYzTm** [comment]
Any progress on the bot?

**Comment by pxwxnvermx** [comment]
@DaYzTm Yeah i have been working on including gallery posts from reddit in bot. Hopefully by the end of this week this issue will be resolved.

**Comment by DaYzTm** [comment]
> @DaYzTm Yeah i have been working on including gallery posts from reddit in bot. Hopefully by the end of this week this issue will be resolved.
> 

Well, that’s very good, I’ll wait, I’m just not very experienced yet.

**Comment by pxwxnvermx** [comment]
@DaYzTm check now. i have added the support there have been some changes the bot can be run from `main.py`from now on.

**Comment by DaYzTm** [comment]
> @DaYzTm check now. i have added the support there have been some changes the bot can be run from `main.py`from now on.
> 

Thank you very much for helping me, so we can close the subject on this occasion
