### ISSUE TITLE
Somehow the library doesn’t work youtubeDL

### ISSUE THREAD

**Issue by sqLDak** [pxwxnvermx/memeboi#4]
I was looking for a bot for autoposting, but I got something wrong, here are the screens.
![изображение](https://user-images.githubusercontent.com/58451297/165538630-f86188ba-1f6f-4893-ba8c-96c49f9f93dc.png)

**Comment by pxwxnvermx** [comment]
@sqLDak hey can you share a larger screen with specific error of ydl

**Comment by sqLDak** [comment]
> @sqLDak hey can you share a larger screen with specific error of ydl

Yeah, but I’m busy after a while.
